version: '3.4'

services:
  deployaimlongcp:
    image: deployaimlongcp
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 demo_requests_test_ML_oct2.py "]
    ports:
      - 5678:5678
